---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - import_tasks: ../../tests/tasks/main.yml
  vars:
    python_bin: /usr/local/bin/python3.9
